server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sintern
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect